backend:
  name: github
  repo: cwkosman/cherin-food-blog

media_folder: static/assets
public_folder: /assets

collections:
  - name: recipes
    label: Recipes
    folder: content/recipes
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: date, label: Date, widget: date }
      - { name: tags, label: Tags, widget: list }
      - { name: featuredImage, label: Featured Image, widget: image }
      - label: Components
        name: components
        widget: list
        fields:
          - name: component
            label: Component
            widget: object
            fields:
              - name: componentTitle
                label: Component Title
                widget: string
                default: Default
              - name: componentIngredientObjects
                label: Component Ingredients
                widget: list
                fields:
                  - name: ingredientObject
                    label: Ingredient
                    widget: object
                    fields:
                      - name: ingredientMachineName
                        label: Ingredient name
                        widget: string
                      - name: ingredientDisplay
                        label: ingredient Display
                        widget: string
      - { name: body, label: Body, widget: markdown }
